/**
 * BatasFlow - Puzzle Generator
 *
 * Deterministic puzzle generator that creates always-solvable Flow puzzles.
 * Algorithm: Generate a Hamiltonian path (visits every cell exactly once)
 * using Warnsdorff's heuristic, then split it into segments.
 * Each segment's endpoints become "dots". Since the solution fills
 * the entire grid, the puzzle is guaranteed solvable.
 */

import { createSeededRandom } from '../sdk';

// ============================================================================
// Types
// ============================================================================

export interface Dot {
  row: number;
  col: number;
  color: string;
  pairId: number;
}

export interface PathCell {
  row: number;
  col: number;
}

export interface FlowPuzzle {
  dots: Dot[];
  solution: Map<number, PathCell[]>;
  gridSize: number;
}

// ============================================================================
// Constants
// ============================================================================

export const FLOW_COLORS = [
  '#EF4444', // red
  '#3B82F6', // blue
  '#22C55E', // green
  '#F59E0B', // amber
  '#A855F7', // purple
  '#EC4899', // pink
  '#06B6D4', // cyan
  '#F97316', // orange
  '#84CC16', // lime
] as const;

const DIRECTIONS: [number, number][] = [
  [-1, 0], // up
  [1, 0],  // down
  [0, -1], // left
  [0, 1],  // right
];

// ============================================================================
// Grid Size → Flow Count Mapping
// ============================================================================

function getFlowRange(gridSize: number): [number, number] {
  switch (gridSize) {
    case 6: return [5, 5];
    case 8: return [7, 7];
    case 10: return [9, 9];
    // Back-compat for legacy sizes (still supported, never generated by current modes)
    case 5: return [4, 5];
    case 7: return [6, 7];
    case 9: return [8, 9];
    default: return [5, 5];
  }
}

// ============================================================================
// Hamiltonian Path Generation (Warnsdorff's Heuristic)
// ============================================================================

/**
 * Generate a Hamiltonian path through the grid using Warnsdorff's heuristic.
 * The path visits every cell exactly once, guaranteeing full grid coverage.
 * Returns null if the greedy approach gets stuck (retry with different start).
 */
function generateHamiltonianPath(
  gridSize: number,
  random: () => number
): PathCell[] | null {
  const totalCells = gridSize * gridSize;
  const visited: boolean[][] = Array.from({ length: gridSize }, () =>
    Array(gridSize).fill(false)
  );

  const startRow = Math.floor(random() * gridSize);
  const startCol = Math.floor(random() * gridSize);

  const path: PathCell[] = [{ row: startRow, col: startCol }];
  visited[startRow][startCol] = true;

  while (path.length < totalCells) {
    const { row, col } = path[path.length - 1];

    // Collect unvisited neighbors with their Warnsdorff scores
    const neighbors: { row: number; col: number; score: number; tiebreak: number }[] = [];
    for (const [dr, dc] of DIRECTIONS) {
      const nr = row + dr;
      const nc = col + dc;
      if (nr >= 0 && nr < gridSize && nc >= 0 && nc < gridSize && !visited[nr][nc]) {
        // Count onward moves from this neighbor (excluding current cell)
        let score = 0;
        for (const [dr2, dc2] of DIRECTIONS) {
          const nnr = nr + dr2;
          const nnc = nc + dc2;
          if (nnr >= 0 && nnr < gridSize && nnc >= 0 && nnc < gridSize && !visited[nnr][nnc]) {
            score++;
          }
        }
        neighbors.push({ row: nr, col: nc, score, tiebreak: random() });
      }
    }

    if (neighbors.length === 0) return null; // stuck

    // Warnsdorff: pick neighbor with fewest onward moves, break ties randomly
    neighbors.sort((a, b) => a.score !== b.score ? a.score - b.score : a.tiebreak - b.tiebreak);

    const next = neighbors[0];
    path.push({ row: next.row, col: next.col });
    visited[next.row][next.col] = true;
  }

  return path;
}

// ============================================================================
// Path Splitting
// ============================================================================

/**
 * Split a Hamiltonian path into flow segments.
 * Each segment has at least 3 cells (non-trivial path between two dots).
 */
function splitIntoFlows(
  fullPath: PathCell[],
  numFlows: number,
  random: () => number
): PathCell[][] {
  const totalCells = fullPath.length;
  const minLen = 3;

  // Ensure we can fit all flows with minimum length
  const maxFlows = Math.floor(totalCells / minLen);
  numFlows = Math.min(numFlows, maxFlows);

  // Each flow gets minLen cells, then distribute remaining randomly
  const extra = totalCells - numFlows * minLen;
  const lengths: number[] = Array(numFlows).fill(minLen);
  for (let i = 0; i < extra; i++) {
    lengths[Math.floor(random() * numFlows)]++;
  }

  const segments: PathCell[][] = [];
  let pos = 0;
  for (const len of lengths) {
    segments.push(fullPath.slice(pos, pos + len));
    pos += len;
  }

  return segments;
}

// ============================================================================
// Puzzle Generation
// ============================================================================

/**
 * Generate a valid, always-solvable Flow puzzle deterministically from a seed.
 *
 * Algorithm:
 * 1. Generate a Hamiltonian path (visits every cell exactly once)
 * 2. Split the path into N segments (one per flow)
 * 3. Each segment's start and end become "dots"
 * 4. The puzzle is guaranteed solvable because the solution fills the entire grid
 */
export function generatePuzzle(
  seed: string,
  params: { gridSize: number }
): FlowPuzzle {
  const { gridSize } = params;
  const random = createSeededRandom(seed);
  const [minFlows, maxFlows] = getFlowRange(gridSize);
  const targetFlows = minFlows + Math.floor(random() * (maxFlows - minFlows + 1));

  // Try to generate a Hamiltonian path (Warnsdorff usually succeeds on first try)
  const maxRetries = 30;
  for (let attempt = 0; attempt < maxRetries; attempt++) {
    const hamiltonianPath = generateHamiltonianPath(gridSize, random);
    if (!hamiltonianPath) continue;

    const segments = splitIntoFlows(hamiltonianPath, targetFlows, random);

    const solution = new Map<number, PathCell[]>();
    const dots: Dot[] = [];

    for (let i = 0; i < segments.length; i++) {
      const seg = segments[i];
      solution.set(i, seg);
      const color = FLOW_COLORS[i % FLOW_COLORS.length];
      dots.push(
        { row: seg[0].row, col: seg[0].col, color, pairId: i },
        { row: seg[seg.length - 1].row, col: seg[seg.length - 1].col, color, pairId: i }
      );
    }

    return { dots, solution, gridSize };
  }

  // Fallback: retry with modified seed (extremely rare)
  return generatePuzzle(seed + '_r', params);
}
