/**
 * Game SDK - Core Types
 * 
 * This module defines the core types and interfaces for the Puzzle Hub platform.
 * All game modules must implement these interfaces to integrate with the platform.
 */

// ============================================================================
// Core Game Types
// ============================================================================

/**
 * Supported game modes for a game.
 */
export interface GameMode {
  modeId: string;
  displayName: string;
  description: string;
  /** Default parameters for this mode */
  defaultParams: GameParams;
}

/**
 * Generic game parameters - base type for game-specific params.
 * Each game defines its own params interface extending this.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface GameParams {}

/**
 * Result of applying an action to game state.
 */
export interface ActionResult<TState> {
  /** The new state after the action */
  state: TState;
  /** Events generated by this action (for replay/verification) */
  events: GameEvent[];
  /** If action was invalid, the reason why */
  invalidReason?: string;
}

/**
 * A game event for logging and replay.
 */
export interface GameEvent {
  type: string;
  payload: unknown;
  timestamp?: number;
}

/**
 * Summary of a completed game run.
 */
export interface GameSummary {
  outcome: 'win' | 'lose' | 'forfeit';
  score: number;
  attemptsUsed: number;
  durationMs: number;
  /** Game-specific summary data */
  details?: Record<string, unknown>;
}

/**
 * Base state that all game states must include.
 */
export interface BaseGameState {
  status: 'playing' | 'won' | 'lost';
  startedAtMs: number;
  endedAtMs: number | null;
}

// ============================================================================
// Game Engine Interface
// ============================================================================

/**
 * Pure, deterministic game engine.
 * 
 * All methods must be pure functions with no side effects.
 * Given the same inputs, they must always produce the same outputs.
 */
export interface GameEngine<TState extends BaseGameState, TAction, TParams extends GameParams = GameParams> {
  /**
   * Initialize a new game state from a seed and parameters.
   * The seed should deterministically produce the same initial state.
   */
  init(seed: string, params: TParams): TState;

  /**
   * Apply an action to the current state.
   * Returns the new state, any events, and validation errors if applicable.
   */
  applyAction(state: TState, action: TAction): ActionResult<TState>;

  /**
   * Check if the game has reached a terminal state (won or lost).
   */
  isTerminal(state: TState): boolean;

  /**
   * Calculate the score for the current state.
   * Only meaningful for terminal states.
   */
  getScore(state: TState, durationMs: number): number;

  /**
   * Generate a summary of the completed game.
   */
  getSummary(state: TState): GameSummary;

  /**
   * Verify a game by replaying actions.
   * Used server-side to validate client-submitted results.
   */
  verify(seed: string, params: TParams, actions: TAction[]): GameSummary;
}

// ============================================================================
// UI Adapter Interface
// ============================================================================

/**
 * Render model for the game UI.
 * This is what the UI components will consume to render the game.
 */
export interface RenderModel {
  /** Current game status */
  status: 'playing' | 'won' | 'lost';
  /** Whether the game is in a terminal state */
  isTerminal: boolean;
  /** Game-specific render data */
  data: Record<string, unknown>;
}

/**
 * Adapts game state to a render model for the UI.
 */
export interface UIAdapter<TState extends BaseGameState> {
  /**
   * Convert game state to a render model.
   * The render model should contain all data needed to render the UI.
   */
  toRenderModel(state: TState): RenderModel;

  /**
   * Get the input configuration (keyboard layout, controls, etc.)
   */
  getInputConfig(): InputConfig;
}

/**
 * Input configuration for the game.
 */
export interface InputConfig {
  type: 'color-picker' | 'keyboard' | 'custom';
  /** Number of colors/options for color-picker type */
  numOptions?: number;
  /** Labels for options */
  optionLabels?: string[];
  /** Color values for color-picker */
  optionColors?: string[];
}

// ============================================================================
// Game Definition Interface
// ============================================================================

/**
 * Complete definition of a game module.
 * This is what gets registered in the game registry.
 */
export interface GameDefinition<
  TState extends BaseGameState = BaseGameState,
  TAction = unknown,
  TParams extends GameParams = GameParams
> {
  /** Unique identifier for the game (e.g., 'wordle', 'mastermind') */
  gameId: string;
  
  /** Display name shown in UI */
  displayName: string;
  
  /** Short description of the game */
  description: string;
  
  /** Icon name (lucide icon) */
  icon: string;
  
  /** Available game modes */
  modes: GameMode[];
  
  /** Supported ruleset versions */
  rulesetVersions: string[];
  
  /** Current/default ruleset version */
  currentRulesetVersion: string;
  
  /** The game engine */
  engine: GameEngine<TState, TAction, TParams>;
  
  /** The UI adapter */
  uiAdapter: UIAdapter<TState>;
  
  /** Whether this game is enabled */
  isEnabled: boolean;
}
